name: Apptainer Build Deploy

on:
  pull_request:
  push:
    branches: main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: quay.io/singularity/singularity:v4.1.0
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4
    
      - name: Build Container
        run: |
           singularity build container.sif Apptainer

      - name: Add ORAS Remote
        run: |
           singularity remote add --no-login ghcr oras://ghcr.io

      - name: Login to ORAS Remote
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin ghcr

      - name: Deploy Container
        run: |
           singularity push container.sif oras://ghcr.io/${{ github.repository }}:${{ github.ref_name }}
